
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker-dev
  
  db:
    image: postgres:14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5    
    ports:
      - "5432:5432"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=nestjs
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
